tests: common_avl: fix a compiler error
[ 82%] Building C object tests/common/CMakeFiles/test_common_avl.dir/test_common_avl.c.o
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c: In function ‘main’:
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
 int main(int argc __attribute__ ((unused)), char **argv __attribute__ ((unused))) {
     ^~~~
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
/home/ferry/vcs/pelagic/oonf/tests/common/test_common_avl.c:883:5: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
cc1: all warnings being treated as errors
make[2]: *** [tests/common/CMakeFiles/test_common_avl.dir/build.make:63: tests/common/CMakeFiles/test_common_avl.dir/test_common_avl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8245: tests/common/CMakeFiles/test_common_avl.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Signed-off-by: Ferry Huberts <ferry.huberts@pelagic.nl>